--- #YAML:1.0
name: AudioFile-Info-Ogg-Vorbis-Header
version: 1.04
author:
  - Dave Cross, E<lt>dave@dave.org.ukE<gt>
abstract: Perl extension to get info from
Ogg Vorbis files.
license: perl
requires:
  AudioFile::Info: 0
  Ogg::Vorbis::Header: 0
  perl: 5.6.0
build_requires:
  Module::Build: 0
provides:
  AudioFile::Info::Build:
    file: lib/AudioFile/Info/Build.pm
  AudioFile::Info::Ogg::Vorbis::Header:
    file: lib/AudioFile/Info/Ogg/Vorbis/Header.pm
    version: 1.04
generated_by: Module::Build version 0.23
