---
name: AudioFile-Info-Ogg-Vorbis-Header
version: 1.08
author:
  - 'Dave Cross, E<lt>dave@dave.org.ukE<gt>'
abstract: |-
  Perl extension to get info from
  Ogg Vorbis files.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  AudioFile::Info: 0
  Ogg::Vorbis::Header: 0
  perl: 5.6.0
build_requires:
  Module::Build: 0
  YAML: 0
provides:
  AudioFile::Info::Build:
    file: lib/AudioFile/Info/Build.pm
    version: 22
  AudioFile::Info::Ogg::Vorbis::Header:
    file: lib/AudioFile/Info/Ogg/Vorbis/Header.pm
    version: 22
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
